### PR TITLE
Enable File-Specific Formatting in dataform format

### PR DESCRIPTION
**Pull request by hiracky16**
resolve https://github.com/dataform-co/dataform/issues/1747
before my pr: https://github.com/dataform-co/dataform/pull/1746

### CODE REVIEW

**Comment by hiracky16** [comment]
Hi @Ekrekr .
I ran the tests, but the following error occurred. It seems like there might be a permission issue. Do you know what might be causing this?

I'm experiencing the same error as this https://github.com/dataform-co/dataform/pull/1751
```
ERROR: /Users/nori/workspace/dataform/test_credentials/BUILD:5:14: Action test_credentials/bigquery.json failed: (Exit 1): gcloud failed: error executing command external/gcloud_sdk/bin/gcloud kms decrypt '--ciphertext-file=test_credentials/bigquery.json.enc' '--plaintext-file=bazel-out/darwin-py2-fastbuild/bin/test_credentials/bigquery.json' ... (remaining 4 arguments skipped)
ERROR: (gcloud.kms.decrypt) PERMISSION_DENIED: Permission 'cloudkms.cryptoKeyVersions.useToDecrypt' denied on resource 'projects/dataform-open-source/locations/global/keyRings/dataform-builder-keyring/cryptoKeys/dataform-builder-key' (or it may not exist).
INFO: Elapsed time: 6.105s, Critical Path: 4.72s
INFO: 15 processes: 15 internal.
FAILED: Build did NOT complete successfully
```

**Comment by Ekrekr** [comment]
Sorry, you won't be able to run these commands yet - there are some privacy and compliance exceptions I need to investigate.

**Comment by hiracky16** [comment]
@Ekrekr 
Understood the current situation. Please investigate. 🙏

**Comment by hiracky16** [comment]
@Ekrekr 
I have been waiting for a response for a week.
Could you please let me know approximately how much longer I should expect to wait?
I appreciate your assistance.

**Review by Ekrekr — APPROVED** [review]

**Comment by Ekrekr** [comment]
> @Ekrekr I have been waiting for a response for a week. Could you please let me know approximately how much longer I should expect to wait? I appreciate your assistance.

Sorry, the process here is killing me.

I've manually tested it for you, and I'll merge it now. Thanks for contributing!

**Pull request merged**
