### PR TITLE
VSCode: avoid errors upon completion requests

### PR DESCRIPTION
**Pull request by barna-emarsys**
While authoring a `.sqlx` file, the VS Code Dataform extension keeps showing error messages about failed completion requests. They read:
```[Error - 18:53:55] Request textDocument/completion failed.
  Message: Unhandled method textDocument/completion
  Code: -32601
```

Here's a demonstration:
dataform_compile_crash_demostration

As far as I see, the issue is caused by the Dataform LSP declaring itself as a completion provider, but never providing a method that provides completions. I could not find any part of the source code that handles completions (the implemented hooks are `onInitialized`, `onRequest("compile")`, `onDidSave` and `onDefinition`). It also seems to me the declarative parts of a language extension can not be responsible for providing completions.

The extension lists as its features: syntax highlighting, compilation and go to definition. All those features continue to work without the LSP declaring itself as a completion provider.

This PR resolves this issue by removing the completion provider declaration.

PS: I have two more PR's ready with suggested features, but I didn't want to overload you with 3 separate PR's at once. 
They would:
- add a configuration setting for specifying the location of the dataform folder within the project
- add a configuration setting to disable compile on save

Are you open to reviewing those as well?

### CODE REVIEW

**Comment by barna-emarsys** [comment]
@GJMcGowan, since you have worked most on the VS Code extension, maybe you can review this PR?

**Review by GJMcGowan — APPROVED** [review]
Thank you for the PR!

You probably noticed that we haven't published a new version of this extension in a while, as we aren't prioritising it's development. That said, this is a good fix and I'm happy to review future work.

I've now submitted a [fix](https://github.com/dataform-co/dataform/pull/1632) that allows the extension to actually build, so I would encourage you in future PRs to build the extension locally and try out the changes (use the commands in CONTRIBUTING.md to create a .vsix file and then install it)

**Comment by barna-emarsys** [comment]
I was actually able to build the `.vsix` file without modifications to the build. I did, however, need to use Docker to virtualize an `x64` Linux environment since I'm on an `arm` mac (see: https://github.com/dataform-co/dataform/issues/1593).

These are the steps I followed:
1) I added the following docker-compose file to the root repository (`docker-compose.yaml`):
```yaml
version: "3.0"

services:
  dev:
    image: node:16
    tty: true
    working_dir: /usr/src/app
    platform: linux/amd64
    volumes:
      - .:/usr/src/app
```

 2)
```
docker compose up -d
docker compose exec dev bash
npm i -g @bazel/bazelisk
bazel run vscode:packager /usr/src/app/dataform.vsix
```

I'm attaching the compiled `.vsix` to this comment (you need to unzip it first): [dataform.vsix.zip](https://github.com/dataform-co/dataform/files/13814484/dataform.vsix.zip).

(PS: I accidentally pushed
 the docker-compose workaround to the branch this PR is requesting to merge. I reverted this commit, since I'm not proposing that this workaround be incorporated into the upstream repo.)

**Comment by GJMcGowan** [comment]
Great! I actually built this locally and it worked fine. I will merge now and do a new release. Thanks!

**Comment by barna-emarsys** [comment]
I've submitted a new PR (https://github.com/dataform-co/dataform/pull/1639) with the 2 new configuration options I've mentioned on this thread. (I used my personal account.)

**Pull request merged**
