### PR TITLE
Add yargs doc for `dataform help` command. Few fixes. [#307]

### PR DESCRIPTION
**Pull request by canetcesc**
Let me know if there are any other commands which require changing the CLI documentation.

### CODE REVIEW

**Comment by BenBirt** [comment]
Thanks Cesc! Just to confirm, this doesn't break `dataform help` or `dataform help <command>`? (yargs doesn't see this as an override of the hack I added to make that work?)

If you're up for it, a small edit to the relevant docs page (https://github.com/dataform-co/dataform/blob/master/docs/pages/guides/command-line-interface.mdx, https://docs.dataform.co/guides/command-line-interface/) to add some details on `dataform help` would also be great, don't feel you need to though.

**Comment by canetcesc** [comment]
1. The CLI seems to work just fine with the new change. For example we can test

`dataform help compile`:

Screenshot 2019-07-24 at 11 08 41

`dataform --help compile`:

Screenshot 2019-07-24 at 11 21 04

`dataform help`:
Screenshot 2019-07-24 at 11 09 54

`dataform --help`:

Screenshot 2019-07-24 at 11 22 45


**Fun fact:** If you try to run a `dataform help help` or `dataform --help help`  "meta-command" you will get the same output as if you just run `dataform help`. That is because the hacky `fixArgvForHelp()` function  will intercept it.  So, the description added in `index.ts` (Line 147) is never displayed to the user.

2. Sure, will add that to the docs.

3. Take a look at my comments on https://github.com/dataform-co/dataform/issues/228, we may want to document `--schema-sufix` in the same change.

**Comment by lewish** [comment]
Hi Cesc, apologies for the delay here, Ben is on holiday :)

**Comment by canetcesc** [comment]
Thanks, @lewish! Be aware that I do not have permissions to merge this, only you can.

**Pull request merged**
