### PR TITLE
refactor: run format to all ts files

### PR DESCRIPTION
**Pull request by kimujun**
Hi @dataform/core 👋

Thank you for this great project! My company has been using @dataform/core as part of our data platform, and it’s been incredibly helpful.

While setting up my local development environment to fix some bugs, I found some formatting inconsistencies in the code.
Since my VSCode is configured to automatically format .ts files on save, these inconsistencies result in unintended diffs.

To avoid these diffs emerging on the bug fixes, I’d like to resolve these formatting issues first.

- [x] `bazel build cli` succeeds
- [x] `bazel test //core/...` succeeds

If there are any other behaviors or checks I need to verify, please let me know.

### CODE REVIEW

**Comment by kimujun** [comment]
@Ekrekr Hi Ekrekr!
I wanted to assign you as a reviewer, but it seems I can’t add reviewers to this PR.
Could you please take a look at it?
image

**Comment by Ceridan** [comment]
@kimujun could you please sign the CLA above? Then you will be able to assign the reviewer.

**Comment by kimujun** [comment]
@Ceridan 
Thank you for your comment. I signed the CLA, and it looks like the CI has confirmed it, but I still can’t assign a reviewer.

image

**Review by Ekrekr — APPROVED** [review]

**Comment by Ekrekr** [comment]
Thank you!

**Pull request merged**
