### PR TITLE
Update analytics-node to unabandoned version

### PR DESCRIPTION
**Pull request by claydiffrient**
This updates to using `@segment/analytics-node` since the other version was abandoned and not receiving  updates.

I followed the [migration guide](https://segment.com/docs/connections/sources/catalog/libraries/server/node/migration/) and believe that I got everything updated that needed to be upgraded.

### CODE REVIEW

**Comment by claydiffrient** [comment]
Github isn't allowing me to request reviewers like the contributing guidelines said to do.  I notice @BenBirt has commented on PRs here... perhaps you can get this to the right place.

I'm also unsure why the tests are failing.  Perhaps something with sensitive credentials or something.  I'm happy to adjust my PR if someone could let me know what needs to change.  Thanks!

**Comment by BenBirt** [comment]
Hi @claydiffrient, thanks for the PR!

Looking at the test failure, I *think* the issue is due to the slightly wonky way we build NPM packages. I believe you need to make a similar change here: https://github.com/dataform-co/dataform/blob/main/packages/%40dataform/cli/BUILD#L36

**Comment by claydiffrient** [comment]
@BenBirt thanks for pointing that out!  I somehow missed that in my search.  I've updated that, but it still appears the test is failing :(

**Comment by BenBirt** [comment]
Looks pretty successful to me! Perhaps a local failure? In any case, LGTM, I am going to merge this.

**Comment by claydiffrient** [comment]
> Looks pretty successful to me! Perhaps a local failure? In any case, LGTM, I am going to merge this.

Oh lol, I didn't refresh the page!  The check flipped to green after I sent that message!

**Comment by BenBirt** [comment]
Thanks for the contribution!

**Pull request merged**
