### PR TITLE
Enable File-Specific Formatting in dataform format

### PR DESCRIPTION
**Pull request by hiracky16**
resolves: https://github.com/dataform-co/dataform/issues/1747

### CODE REVIEW

**Comment by hiracky16** [comment]
@BenBirt

I hope this message finds you well.
This is my first pull request to the repository, and I noticed that the CI check has failed.
It appears that the CI process did not run at all, leading to an error.

Could you please help me understand the possible reasons for this issue?
I would like to resolve any problems and ensure that the PR meets the repository's requirements.

**Comment by Ekrekr** [comment]
> @BenBirt
> 
> I hope this message finds you well. This is my first pull request to the repository, and I noticed that the CI check has failed. It appears that the CI process did not run at all, leading to an error.
> 
> Could you please help me understand the possible reasons for this issue? I would like to resolve any problems and ensure that the PR meets the repository's requirements.

We just updated our CI progress, and you're the first to test it! Unfortunately, it's not working for external contributors, and I'm not sure why...

You can run tests manually for now by running `./scripts/run_tests`.

**Comment by hiracky16** [comment]
@Ekrekr 
Thank you for your assistance.

I have accepted your suggestion and would appreciate another review. 🙏
Additionally, I tried running the tests locally, but they seem to be failing.
How can I run tests? 

The error message is as follows:
```
ERROR: /Users/nori/workspace/dataform/test_credentials/BUILD:5:14: Action test_credentials/bigquery.json failed: (Exit 1): gcloud failed: error executing command external/gcloud_sdk/bin/gcloud kms decrypt '--ciphertext-file=test_credentials/bigquery.json.enc' '--plaintext-file=bazel-out/darwin-py2-fastbuild/bin/test_credentials/bigquery.json' ... (remaining 4 arguments skipped)
ERROR: (gcloud.kms.decrypt) PERMISSION_DENIED: Permission 'cloudkms.cryptoKeyVersions.useToDecrypt' denied on resource 'projects/dataform-open-source/locations/global/keyRings/dataform-builder-keyring/cryptoKeys/dataform-builder-key' (or it may not exist).
```

**Comment by Ekrekr** [comment]
Can you share me your gmail account, and I'll grant you permission to decrypt the secret, and to run the tests? Thanks!

**Comment by hiracky16** [comment]
@Ekrekr 
My Gmail account is the same as my GitHub email address. Please share accordingly.
If possible, if you could also share the steps to run the CI/CD after the decrypt is shared.

**Comment by hiracky16** [comment]
@Ekrekr 
My Google Account is h.piiice16@gmail.com .
Please grant you permission.

**Comment by Ekrekr** [comment]
> @Ekrekr My Google Account is [h.piiice16@gmail.com](mailto:h.piiice16@gmail.com) . Please grant you permission.

Hi Noriaki,

I've granted some permissions for people in the `dataform-open-source-contributors` Google group. If everything works, you should now be able to:
* Run `./scripts/run_tests`.
* Re-run the `pull-request-trigger` failed CI - you might need to accept cla/google first, to get that one green.

Let me know if this works!

Thanks.

**Comment by hiracky16** [comment]
I will reopen the PR because the cla/google CI is failing.

**Pull request closed without merging**
