### PR TITLE
Fix vscode extension crashes on windows

### PR DESCRIPTION
**Pull request by moker-spaghetti**
1. Fix command name on windows to "dataform.cmd".
2. Add error handling to prevent whole extension crash.

I'm not sure how to run linter (I tried to run `scripts/lint`, but it ended up with an error `could not require "tslint-config-prettier".`), so I'd appreciate any advice you can offer.
Also, since this is my first PR to this project, please let me know if you notice any issues.

### CODE REVIEW

**Comment by Ekrekr** [comment]
> 1. Fix command name on windows to "dataform.cmd".
> 2. Add error handling to prevent whole extension crash.
> 
> I'm not sure how to run linter (I tried to run `scripts/lint`, but it ended up with an error `could not require "tslint-config-prettier".`), so I'd appreciate any advice you can offer. Also, since this is my first PR to this project, please let me know if you notice any issues.

I think we don't actually have any tests for the VSCode extension, looking at the `vscode/BUILD` file!

Can you share me your gmail address, and I will allowlist you to run the tests and CI pipeline anyway? You will be able to merge after that.

I've assigned @GJMcGowan for review, as he is able to publish changes.

**Comment by moker-spaghetti** [comment]
@Ekrekr My gmail address is moker0spaghetti@gmail.com, thank you!

**Comment by moker-spaghetti** [comment]
@Ekrekr Thank you for the invitation to the group. I signed into the above account with `gcloud auth login` and run `scripts/run_tests`, but it ended up in the error below.
```
ERROR: /workspaces/dataform/test_credentials/BUILD:5:14: Action test_credentials/bigquery.json failed: (Exit 1): gcloud failed: error executing command external/gcloud_sdk/bin/gcloud kms decrypt '--ciphertext-file=test_credentials/bigquery.json.enc' '--plaintext-file=bazel-out/k8-py2-fastbuild/bin/test_credentials/bigquery.json' ... (remaining 4 arguments skipped)
ERROR: (gcloud.kms.decrypt) PERMISSION_DENIED: Permission 'cloudkms.cryptoKeyVersions.useToDecrypt' denied on resource 'projects/dataform-open-source/locations/global/keyRings/dataform-builder-keyring/cryptoKeys/dataform-builder-key' (or it may not exist).
```
Also, I could not see any project listed in my Google Cloud Console.
Do you have any advice?

**Comment by Ekrekr** [comment]
Hi Moker,

I've granted some permissions for people in the `dataform-open-source-contributors` Google group. If everything works, you should now be able to:
* Run `./scripts/run_tests`.
* Re-run the `pull-request-trigger` failed CI.

Let me know if this works!

Thanks.

**Comment by Ekrekr** [comment]
Sorry, you won't be able to run these commands yet - there are some privacy and compliance exceptions I need to investigate.

**Pull request merged**
